added services, endpoints without tests
jekaslav/ReservationSystem.API pull request #1
Opened 2023-05-05 10:15 UTC by jekaslav

2023-05-05 11:44 UTC, Pavlukash requested changes

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ChiefService.cs
> +            if (!chiefs.Any())
Чифов может просто не быть в бд, это тоже приемлимый сценарий, поэтому тут не надо проверку с киданием эксепшена. Убери эту проверку и в остальных GetAll методах

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ChiefService.cs
> +            if (id <= 0)
В этой проверке также нет смысла, достаточно будет проверки на налл, которая есть ниже. Убери эту проверку и в других методах тоже

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ChiefService.cs
> +                throw new KeyNotFoundException();
В будущем тебе надо будет научиться писать кастомные эксепшены и обрабатывать их через специальный мидлвэр. На данном этапе упустим это. В этой проверке ты смотришь, является ли объект налл, поэтому тут уместнее кидать NullReferenceException. Поправь это и в других методах с подобной проверкой

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ChiefService.cs
> +        public async Task<ChiefDto> GetChiefsById(int id, CancellationToken cancellationToken)
Поправь нейминг метода и переменной chiefs, что будет ниже. В данном методе ты возвращаешь всего одного чифа, поэтому убери множественное число. Неправильный нейминг может вводить в заблуждение

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ChiefService.cs
> +            if (string.IsNullOrWhiteSpace(chiefDto.Name))
Добавь в условие метода проверку мейла тоже. На данном этапе гипотетически может прийти Дто с именем, но с пустым мейлом и данный сценарий ты никак не обрабатываешь

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ChiefService.cs
> +            var classroomToControl = await ReservationDbContext.Classrooms.FindAsync(classroomId);
Используй FirstOrDefaultAsync как использовал до этого. Никаких FindAsync

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ChiefService.cs
> +            if (chief == null || classroomToControl == null)
Проверяй на налл каждый объект в отдельном ифе и кидай NullReferenceException

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ChiefService.cs
> +                Classroom = classroomToControl
Здесь тебе надо приравнивать не сами объекты, а их айдишники, так как имеено они будут храниться в бд и именно с ними небходмио будет в будущем взаимодействовать. Именно для этого ты и прописывал HasForeignKey, когда создавал связи в контексте

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ChiefService.cs
> +                return false;
NullReferenceException

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Services/Services/ClassroomService.cs
> +        {
Добавь валидацию приходящей в параметрах Дто

2023-05-05 11:44 UTC, Pavlukash commented on ReservationSystem.Domain/Entities/ReservationEntity.cs
> +    {
Добавь айди у самой энтити

2023-05-08 12:25 UTC, nikolay-tsay requested changes

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.API/Controllers/ReservationRequestController.cs
> +            if (!Enum.IsDefined(typeof(ReservationStatus), newStatus))
Вместо int, имеет смысл принимать сразу тип enum ReservationStatus, тогда можно будет убрать этот иф с контроллера(никаких ифов в эндпоинтах быть не должно). В сервисе достаточно будет сделать проверку что статус выставляется не на "В ожидании"

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Domain/Entities/ChiefEntity.cs
> +        // }
Удали комент

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Domain/Entities/ClassroomEntity.cs
> +        // }
Комент удалить

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Domain/Entities/ReservationRequestEntity.cs
> +        }
Конструкторов у энтити быть не должно, если хочешь дефолтное значени, то пропиши его в контексте

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Domain/Entities/ReservationRequestEntity.cs
> +        public ClassroomEntity Classroom { get; set; }
Почему JsonIgnore? Вроде бы нигде эта энтити в json не уходит

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Services/Services/ChiefService.cs
> +            if (id <= 0)
На самом деле смысл в ней есть, id приходит с фронта, то есть это может быть буквально любое число, так что можно и оставить, только тип эксепшена должен быть BadRequest

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Services/Services/ChiefService.cs
> +                throw new KeyNotFoundException();
В условии ифа поменяй chiefs == null на chiefs is null, если получится, не уверен что в .net 5 так можно

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Services/Services/ChiefService.cs
> +            var classroomToControl = await ReservationDbContext.Classrooms.FindAsync(classroomId);
Тут скорее вопрос постоянства, в FindAsync нет ничего плохого, если поиск происходит по какому-нибудь индексу. Но в остальных методах ты используешь FirstOrDefaultAsync, так что его и используй

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Services/Services/ChiefService.cs
> +                Classroom = classroomToControl
А еще айдишников нам достаточно, т.е. ни чифа, ни аудиторию дергать не обязательно. Если их не существет, бд не даст тебе сохранить этот объект, потому что не пройдет валидация внешнего ключа. Так что, можно просто приравнять айдишники и все

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Services/Services/ReservationRequestService.cs
> +                .FirstOrDefaultAsync(x => x.ClassroomId == classroomId && x.ChiefId == chiefId, cancellationToken);
Одно из условий вытащи в .Where, старайся использовать && || как можно режже

2023-05-08 12:25 UTC, nikolay-tsay commented on ReservationSystem.Services/Services/ReservationRequestService.cs
> +            var success = await CreateReservation(request.StudentId, request.ClassroomId, request.StartTime, request.EndTime, cancellationToken);
1. Мне не нравится, что в классе запросов на резервацию есть метод создающий резервацию. Будет лучше, если здесь будет зваться метод из  ReservationService, который создаст нам резервацию.
2. В методе CreateReservation ты сохраняешь изменения - делаешь SaveChangesAsync. В конце метода ты делаешь это еще раз. Так делать нельзя, измения должны сохраниться одновременно или не сохраниться вообще, потому что они зависят друго от друга. Оставить один SaveChangesAsync у тебя не получиться из-за пункта 1. Поэтому тебе нужно, чтобы изменения здесь сохранились одновременно в транзакции

2023-05-09 11:10 UTC, Pavlukash requested changes

2023-05-09 11:10 UTC, Pavlukash commented on ReservationSystem.Services/Services/ReservationService.cs
> +                .Where(x => x.ClassroomId == classroomId && x.StartTime < endTime && x.EndTime > startTime)
Раздроби Where на несколько

2023-05-09 11:10 UTC, Pavlukash commented on ReservationSystem.Services/Services/ReservationService.cs
> +            if (existingReservation != null)
Замени "!=" на "is not"

2023-05-09 11:10 UTC, Pavlukash commented on ReservationSystem.Services/Services/ReservationService.cs
> +                return false;
Тут бы лучше кидать эксепшн

2023-05-09 16:24 UTC, nikolay-tsay approved these changes

2023-05-09 16:24 UTC, nikolay-tsay commented on ReservationSystem.Services/Services/ReservationRequestService.cs
> +                    return false;
Ни в коем случае здесь не может быть return, у тебя останется висеть транзакция, кидай эксепшн, процесс уйдет в catch и обработает ошибку

2023-05-09 16:24 UTC, nikolay-tsay commented on ReservationSystem.Services/Services/ReservationRequestService.cs
> +                throw;
А вот здесь как раз логичнее вернуть false

2023-05-09 21:08 UTC, Pavlukash approved these changes

2023-05-09 21:09 UTC, merged